name: Pages
on:
  push: { branches: [ "main" ] }
  workflow_dispatch:
concurrency: { group: pages, cancel-in-progress: true }
permissions: { contents: read, pages: write, id-token: write }
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Pick pages dir
        id: pick
        run: |
          # 静的ファイルなのでルートディレクトリをそのまま使用
          echo "dir=." >> $GITHUB_OUTPUT
      - uses: actions/upload-pages-artifact@v3
        with: { path: . }
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: { name: github-pages, url: ${{ steps.deployment.outputs.page_url }} }
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4