name: Release
on:
  push: { tags: [ 'v*.*.*' ] }
jobs:
  build-package:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - name: Archive
        run: |
          mkdir -p artifact
          tar --exclude-vcs --exclude='.github' -czf artifact/3sisters-restaurant-app-${GITHUB_REF_NAME}.tar.gz .
          (cd artifact && sha256sum *.tar.gz > SHA256SUMS.txt)
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifact/*.tar.gz
            artifact/SHA256SUMS.txt
          body: |
            ## 🍽️ 3姉妹レストラン決定アプリ ${GITHUB_REF_NAME}
            
            ### 📱 使い方
            1. ZIPをダウンロード・解凍
            2. `python -m http.server 8000` または `npx serve .`
            3. ブラウザで http://localhost:8000 にアクセス
            4. パスワード: `3sisters`
            
            ### 📱 PWA機能
            - Safari → 共有 → ホーム画面に追加でアプリ化
            - オフライン対応
            
            **チェックサム**: SHA256SUMS.txtで検証可能